* Introduction
  This is to keep track of notes while I work through sicp
* Ch1 - Building Abstractions with Procedures
** Interpretor Evaluation of Combinations
   1. Evaluate the subexpressions of the combination
   2. Apply the procedure that is the value of the leftmost subexpression (the operator)
       to the arguments that are the values of the other subexpressions (the operands)
** Substitution Model
    A model to determine the "meaning" of procedure application.

    To apply a compound procedure to arguments, evaluate the
    body of the procedure with each formal parameter replaced
    by the corresponding argument.

    For procedure applications that can be modeled using substitution and that yield
    legitimate vlaues, normal-order and applicative order evaluation produce
    the same value.

*** Normal-order evaluation
    Fully expand operand expressions for parameters until an expression of only
    primitive opperators then reduce for evaluation.
    "Fully expand and then reduce"

*** Applicative-order evaluation
    Method the interpreter actually uses.
    "Evaluate the arguments and then apply"


    
      
    
   
   
    

