#+STARTUP: showall
Exercise 1.15
* Part a
** Q
   How many times is procedure p applied when (sine 12.15) is evaluated?
** A
   For everytime angle is > 0.1, p is applied, and every recurive call
   divides angle by 3.0, thus

   ==> 12.15/(3.0^n) <= 0.1
   ==> n >= 4.36907
   
   since n must be an integer, ceil(4.36907) = 5, thus p is applied 5 times
   when evaluated.

* Part b
** Q
   What is the order of growth in space and number of steps (as a function
   of a) used by the process generated by the sine procedure when (sine a) is 
   evaluated?
** A
   In terms of algorithmic complexity regarding logarithms, change of base
   allows logs of different base to differ by only a constant multiplier, which
   in Big O notation would be discarded.

   Thus both space and time complexity is O(log(a)) since a is divided by 3 
   each time the function is called until a <= 0.1.

   The exact number of steps required is given from part a, mainly:
   (ceiling(/ (log (/ a 0.1)) (log 3)))
   
